services:
  - type: web
    name: frontend-todo
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run preview
    staticPublicPath: /dist
    routes:
      - path: /*
        destination: /index.html
